### ISSUE TITLE
Error cv::contourArea

### ISSUE THREAD

**Issue by khacson** [DevashishPrasad/LCD-OCR#2]
$ python code.py
Traceback (most recent call last):
  File "code.py", line 47, in <module>
    if cv2.contourArea(c) < 600:
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

[ WARN:1] terminating async callback

**Comment by DevashishPrasad** [comment]
This is happening because of version issues. You may find some solutions 
[here](https://stackoverflow.com/questions/39475125/compatibility-issue-with-contourarea-in-opencv-3)

**Comment by Raj3142** [comment]
> $ python code.py
> Traceback (most recent call last):
> File "code.py", line 47, in
> if cv2.contourArea(c) < 600:
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'
> 
> [ WARN:1] terminating async callback



> $ python code.py
> Traceback (most recent call last):
> File "code.py", line 47, in
> if cv2.contourArea(c) < 600:
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'
> 
> [ WARN:1] terminating async callback

Getting same error. Please help

**Comment by DevashishPrasad** [comment]
Please go through the following link
https://stackoverflow.com/questions/39475125/compatibility-issue-with-contourarea-in-opencv-3

In Opencv 3 API version the cv2.findContours() returns 3 objects

Check you Opencv version
